### PR TITLE
Migrating to Apache DS 2.0.0.AM27 and LDAP API 2.1.5

### PR DESCRIPTION
**Pull request by coheigea**

### CODE REVIEW

**Comment by coheigea** [comment]
@elecharny Do you know why the LDAP tests in Kerby would fail on updating Apache DS with:
```
2023-10-26T15:00:36.5217069Z java.lang.NoSuchFieldException: classDirectoryService
2023-10-26T15:00:36.5217749Z 	at java.lang.Class.getField(Class.java:1703)
2023-10-26T15:00:36.5218991Z 	at org.apache.directory.server.core.integ.ApacheDSTestExtension.setDirectoryService(ApacheDSTestExtension.java:81)
2023-10-26T15:00:36.5220737Z 	at org.apache.directory.server.core.integ.ApacheDSTestExtension.beforeAll(ApacheDSTestExtension.java:179)
```

**Comment by elecharny** [comment]
Hi Colm,

I have changed the test framework from junit4 to junit5. 

The class that were using @RunWith(FrameworkRunner.class) should now use @ExtendWith( ApacheDSTestExtension.class )

I think this is the pb you have.

**Comment by coheigea** [comment]
@elecharny It's not the problem, the PR upgrades to ApacheDSTestExtension :-)

**Comment by elecharny** [comment]
@coheigea Sorry, a bit busy those days. I'll have a look at it in the coming days.

**Comment by elecharny** [comment]
@coheigea be sure that the test class extends _AbstractLdapTestUnit_. I had to declare the fields in this class as static members.

(or you can move the code from this class to one of the class you extend)

Don't ask, the Junit4 -> Junit5 migration was an ugly mess :/

**Comment by coheigea** [comment]
@elecharny Thanks, I've been able to work around it with that hint

**Comment by elecharny** [comment]
Sorry for the time it took me to analyze the issue. Actually, another Apache fellow had the same issue last week, so I spent the couple of hours to understand the root cause.

Glad it worked!

**Pull request merged**
