### PR TITLE
DIRKRB-746

### PR DESCRIPTION
**Pull request by liujiayi771**
The remote kadmin tool of HAS should only allow the principal of kadmin

### CODE REVIEW

**Comment by plusplusjiajia** [comment]
@liujiayi771 As we discussed offline, do you have any improvements to avoid some configurations in Krb5LoginModule change the principal?

**Comment by liujiayi771** [comment]
> @liujiayi771 As we discussed offline, do you have any improvements to avoid some configurations in Krb5LoginModule change the principal?

I have added a check for kadmin principal on the server side.

**Comment by plusplusjiajia** [comment]
@liujiayi771 The TestKadminApi failed with this patch, could you look at it?

image

**Comment by liujiayi771** [comment]
> @liujiayi771 The TestKadminApi failed with this patch, could you look at it?
> 
> image

When filter_auth_type is not kerberos, there is no need to check the admin principal. I also added the processing when the request principal is null.

**Comment by plusplusjiajia** [comment]
LGTM. I will merge the PR. Thanks for your contribution. @liujiayi771

**Pull request closed without merging**
