### PR TITLE
[DIRKRB-741] Asn1Utf8String incorrectly calculates value length

### PR DESCRIPTION
**Pull request by michael-o**

### CODE REVIEW

**Review by coheigea — CHANGES_REQUESTED** [review]
Can you add a unit test to the PR based on the test code you gave in the JIRA?

**Comment by michael-o** [comment]
Yes, sure. Let me have a look at this later this day.

**Comment by michael-o** [comment]
@coheigea There it is. Have a look.

**Comment by elecharny** [comment]
I'm afraid your test does not cover a String which length > 127.

**Comment by michael-o** [comment]
> 
> 
> I'm afraid your test does not cover a String which length > 127.

Shall I add one?

**Comment by michael-o** [comment]
@elecharny Done.

**Pull request merged**
