### PR TITLE
DIRKRB-765 - Remove has project

### PR DESCRIPTION
**Pull request by coheigea**

### CODE REVIEW

**Comment by gaoshq7** [comment]
Why delete this module, I currently want to use this related function, some worry

**Comment by coheigea** [comment]
What related function do you need to use? The has project was not maintained, and is not really related to kerby anyway.

**Comment by gaoshq7** [comment]
> What related function do you need to use? The has project was not maintained, and is not really related to kerby anyway.

I have my own user system, so I don't want to maintain another user system, and let the hadoop ecosystem can identify my users, the has module provides user plug-ins, just to achieve my needs

**Comment by coheigea** [comment]
Maybe another maintainer of the project will appear and we can revert the change...

**Comment by gaoshq7** [comment]
> Maybe another maintainer of the project will appear and we can revert the change...

Well, I can try. Maybe I can be that guy 😊

**Pull request merged**
